"""
User Bash Monitor - User shell command context injection.

Stores user shell command outputs and injects them into LLM context
following Claude Code's pattern for intent awareness.
"""

import logging
from dataclasses import dataclass
from typing import List, Optional
from .base_monitor import BaseMonitor
from backend.shared.utils.shell import truncate_output

logger = logging.getLogger(__name__)

# Caveat message matching Claude Code's design
CAVEAT_MESSAGE = """Caveat: The messages below were generated by the user while running local commands.
DO NOT respond to these messages or otherwise consider them in your response
unless the user explicitly asks you to."""


@dataclass
class BashContext:
    """Single bash command context."""
    command: str
    stdout: str
    stderr: str


class UserBashMonitor(BaseMonitor):
    """
    Monitor for user shell command context injection.

    Stores user-executed shell commands (! prefix) and their outputs,
    injecting them into LLM context so the AI can "see" user operations.

    Design follows Claude Code's pattern:
    - User operations are visible to LLM (intent awareness)
    - Default: don't respond to shell output (reduce noise)
    - User can explicitly ask about the output (flexibility)
    """

    def __init__(self, session_id: str):
        """
        Initialize user bash monitor.

        Args:
            session_id: Session ID for scoped monitoring
        """
        super().__init__(session_id)
        self._contexts: List[BashContext] = []

    def add_context(self, command: str, stdout: str, stderr: str) -> None:
        """
        Add a shell command context for injection.

        Args:
            command: The shell command executed
            stdout: Standard output from the command
            stderr: Standard error from the command
        """
        self._contexts.append(BashContext(
            command=command,
            stdout=truncate_output(stdout),
            stderr=truncate_output(stderr),
        ))
        logger.debug(f"Added bash context for command: {command[:50]}...")

    def clear_contexts(self) -> None:
        """Clear all stored contexts."""
        self._contexts.clear()

    def has_contexts(self) -> bool:
        """Check if there are any pending contexts."""
        return len(self._contexts) > 0

    def _format_context(self, ctx: BashContext) -> str:
        """
        Format a single bash context in Claude Code style.

        Args:
            ctx: The bash context to format

        Returns:
            Formatted string with bash-input/stdout/stderr tags
        """
        return (
            f"<bash-input>{ctx.command}</bash-input>\n"
            f"<bash-stdout>{ctx.stdout}</bash-stdout>\n"
            f"<bash-stderr>{ctx.stderr}</bash-stderr>"
        )

    async def get_reminders(self) -> List[str]:
        """
        Get user bash contexts as reminder blocks.

        Contexts are consumed (cleared) after retrieval to prevent
        duplicate injection.

        Returns:
            List[str]: Formatted system-reminder blocks
        """
        if not self._contexts:
            return []

        # Format all contexts
        formatted_contexts = [
            self._format_context(ctx) for ctx in self._contexts
        ]

        # Combine with caveat
        combined = CAVEAT_MESSAGE + "\n\n" + "\n\n".join(formatted_contexts)

        # Wrap in system-reminder block
        reminder_block = f"<system-reminder>\n{combined}\n</system-reminder>"

        # Clear contexts after retrieval (consume once)
        context_count = len(self._contexts)
        self._contexts.clear()

        logger.info(f"Injected {context_count} user bash context(s)")

        return [reminder_block]


# Registry for session-scoped monitors (separate from StatusMonitor registry)
_user_bash_monitors: dict[str, UserBashMonitor] = {}


def get_user_bash_monitor(session_id: str) -> UserBashMonitor:
    """
    Get or create a UserBashMonitor for a session.

    This function allows Shell API to access the monitor directly
    for adding contexts without going through StatusMonitor.

    Args:
        session_id: Session ID

    Returns:
        UserBashMonitor: Session-scoped monitor instance
    """
    if session_id not in _user_bash_monitors:
        _user_bash_monitors[session_id] = UserBashMonitor(session_id)
    return _user_bash_monitors[session_id]


def clear_user_bash_monitor(session_id: str) -> None:
    """
    Clear user bash monitor for a session.

    Should be called when session is deleted.

    Args:
        session_id: Session ID
    """
    if session_id in _user_bash_monitors:
        del _user_bash_monitors[session_id]
