"""LLM context injection format for shell commands.

Provides Claude Code-compatible format for injecting shell command
results into LLM conversation context.

Format matches Claude Code exactly:
    <bash-input>command</bash-input>
    <bash-stdout>output</bash-stdout>
    <bash-stderr>errors</bash-stderr>

This format is used by:
- Agent's bash tool (backend) - for tool results
- User's shell commands (CLI) - for context injection
"""

from typing import Optional
from .result import ShellExecutionResult


# Caveat message matching Claude Code's exact wording
SHELL_CAVEAT_MESSAGE = (
    "Caveat: The messages below were generated by the user while running local commands. "
    "DO NOT respond to these messages or otherwise consider them in your response "
    "unless the user explicitly asks you to."
)


def format_for_llm_context(
    command: str,
    stdout: str,
    stderr: str,
) -> str:
    """Format shell execution result for LLM context injection.

    Generates Claude Code-compatible XML format that can be injected
    into the conversation context.

    Args:
        command: The command that was executed
        stdout: Standard output from the command
        stderr: Standard error from the command

    Returns:
        Formatted string in Claude Code XML format

    Example:
        >>> format_for_llm_context("git status", "On branch main", "")
        '<bash-input>git status</bash-input>
        <bash-stdout>On branch main</bash-stdout>
        <bash-stderr></bash-stderr>'
    """
    return (
        f"<bash-input>{command}</bash-input>\n"
        f"<bash-stdout>{stdout}</bash-stdout>\n"
        f"<bash-stderr>{stderr}</bash-stderr>"
    )


def format_from_result(result: ShellExecutionResult) -> str:
    """Format ShellExecutionResult for LLM context injection.

    Convenience wrapper around format_for_llm_context that takes
    a ShellExecutionResult object.

    Args:
        result: Shell execution result

    Returns:
        Formatted string in Claude Code XML format
    """
    return format_for_llm_context(
        command=result.command,
        stdout=result.stdout,
        stderr=result.stderr,
    )


def format_caveat_message() -> str:
    """Get the caveat message for user shell commands.

    This message instructs the LLM to not respond to the shell output
    unless explicitly asked by the user.

    Returns:
        Caveat message string
    """
    return SHELL_CAVEAT_MESSAGE


def format_with_caveat(
    command: str,
    stdout: str,
    stderr: str,
) -> str:
    """Format shell result with caveat prefix for user commands.

    Used when injecting user's shell command results into context.
    The caveat tells LLM to not automatically respond.

    Args:
        command: The command that was executed
        stdout: Standard output from the command
        stderr: Standard error from the command

    Returns:
        Formatted string with caveat prefix

    Example:
        >>> format_with_caveat("ls", "file1.txt", "")
        'Caveat: The messages below were generated...
        <bash-input>ls</bash-input>
        <bash-stdout>file1.txt</bash-stdout>
        <bash-stderr></bash-stderr>'
    """
    context = format_for_llm_context(command, stdout, stderr)
    return f"{SHELL_CAVEAT_MESSAGE}\n{context}"
