"""
PFC Plot Capture Script Template

This module provides script generation for the pfc_capture_plot tool.
Scripts are generated dynamically based on parameters and executed in PFC.

Design Philosophy:
- Create temporary plot to avoid interfering with user's plots
- Include sensible defaults for ball, wall visualization
- Support customizable view settings
- Auto-cleanup temporary plot after export
"""

from typing import Dict, Any, List, Tuple, Optional


# Default plot configuration
DEFAULT_PLOT_NAME = "NagisaDiagnostic"
DEFAULT_WALL_TRANSPARENCY = 70  # 0-100, 70 = 70% transparent
DEFAULT_IMAGE_SIZE = (1920, 1080)


def generate_plot_capture_script(
    output_path: str,
    plot_name: str = DEFAULT_PLOT_NAME,
    size: Tuple[int, int] = DEFAULT_IMAGE_SIZE,
    view_settings: Optional[Dict[str, Any]] = None,
    include_ball: bool = True,
    include_wall: bool = True,
    include_axes: bool = True,
    wall_transparency: int = DEFAULT_WALL_TRANSPARENCY,
) -> str:
    """
    Generate Python script for PFC plot capture.

    Creates a temporary plot, adds visualization items, exports as PNG,
    then deletes the temporary plot.

    Args:
        output_path: Absolute path for output PNG file (forward slashes)
        plot_name: Name for temporary plot (default: "NagisaDiagnostic")
        size: Image dimensions (width, height)
        view_settings: Optional view parameters dict with keys:
            - center: (x, y, z) camera look-at point
            - eye: (x, y, z) camera position
            - distance: float, distance from center
            - dip: float, view plane dip angle in degrees
            - dip_direction: float, dip direction in degrees
            - roll: float, camera roll angle in degrees
            - magnification: float, zoom level (1.0 = normal)
            - projection: "perspective" or "parallel"
        include_ball: Add ball visualization item
        include_wall: Add wall visualization item with transparency
        include_axes: Add coordinate axes
        wall_transparency: Wall transparency 0-100 (default: 70)

    Returns:
        Python script content as string
    """
    lines: List[str] = [
        '"""',
        'PFC Plot Capture Script',
        'Generated by pfc_capture_plot tool',
        '',
        'This script creates a temporary diagnostic plot, exports it as PNG,',
        'then deletes the temporary plot to avoid cluttering the workspace.',
        '"""',
        '',
        'import itasca',
        'import os',
        '',
        '# Configuration',
        f'output_path = r"{output_path}"',
        f'plot_name = "{plot_name}"',
        '',
        '# Ensure output directory exists',
        'os.makedirs(os.path.dirname(output_path), exist_ok=True)',
        '',
    ]

    # Create plot section
    lines.extend([
        '# Create temporary diagnostic plot',
        f'itasca.command(\'plot create "{plot_name}"\')',
        f'itasca.command(\'plot background "white"\')',
        '',
    ])

    # View settings section
    lines.append('# Set view')
    view_cmd_parts = _build_view_command(view_settings)
    if view_cmd_parts:
        # Apply custom view settings
        lines.append(f'itasca.command(\'plot view {view_cmd_parts}\')')
    else:
        # Default: isometric view (standard engineering visualization)
        lines.append('itasca.command(\'plot view isometric\')')
    lines.append('')

    # Add plot items section
    lines.append('# Add visualization items')

    if include_ball:
        lines.append('itasca.command(\'plot item create ball\')')

    if include_wall:
        lines.append(f'itasca.command(\'plot item create wall transparency {wall_transparency}\')')

    if include_axes:
        lines.append('itasca.command(\'plot item create axes\')')

    lines.append('')

    # Export section
    lines.extend([
        '# Export plot as PNG',
        f'itasca.command(f\'plot "{plot_name}" export bitmap filename "{{output_path}}" size {size[0]} {size[1]}\')',
        '',
    ])

    # Cleanup section
    # Syntax: plot <name> delete (name before delete keyword)
    lines.extend([
        '# Delete temporary plot',
        f'itasca.command(\'plot "{plot_name}" delete\')',
        '',
        'print(f"Plot captured successfully: {output_path}")',
    ])

    return '\n'.join(lines)


def _build_view_command(view_settings: Optional[Dict[str, Any]]) -> str:
    """
    Build view command string from settings dict.

    Args:
        view_settings: Dict with view parameters (center, eye, distance, etc.)

    Returns:
        View command parameters string, or empty string if no settings
    """
    if not view_settings:
        return ""

    parts: List[str] = []

    # Projection mode (perspective or parallel)
    if "projection" in view_settings:
        parts.append(f"projection {view_settings['projection']}")
    else:
        parts.append("projection perspective")

    # Camera position
    if "center" in view_settings:
        c = view_settings["center"]
        parts.append(f"center ({c[0]},{c[1]},{c[2]})")

    if "eye" in view_settings:
        e = view_settings["eye"]
        parts.append(f"eye ({e[0]},{e[1]},{e[2]})")

    # View parameters
    if "distance" in view_settings:
        parts.append(f"distance {view_settings['distance']}")

    if "magnification" in view_settings:
        parts.append(f"magnification {view_settings['magnification']}")

    if "dip" in view_settings:
        parts.append(f"dip {view_settings['dip']}")

    if "dip_direction" in view_settings:
        parts.append(f"dip-direction {view_settings['dip_direction']}")

    if "roll" in view_settings:
        parts.append(f"roll {view_settings['roll']}")

    return " ".join(parts)


# Future extensions (placeholders for advanced features)

def generate_stress_visualization_script(
    output_path: str,
    stress_component: str = "maximum",  # maximum, minimum, mean, deviatoric
    **kwargs
) -> str:
    """
    Generate script for stress field visualization.

    Future feature: Color balls by contact stress.
    """
    raise NotImplementedError("Stress visualization not yet implemented")


def generate_velocity_visualization_script(
    output_path: str,
    velocity_component: str = "magnitude",  # magnitude, x, y, z
    **kwargs
) -> str:
    """
    Generate script for velocity field visualization.

    Future feature: Arrow plot for velocity vectors.
    """
    raise NotImplementedError("Velocity visualization not yet implemented")


def generate_contact_force_script(
    output_path: str,
    force_type: str = "normal",  # normal, shear, total
    **kwargs
) -> str:
    """
    Generate script for contact force chain visualization.

    Future feature: Force chain network display.
    """
    raise NotImplementedError("Contact force visualization not yet implemented")
