"""
Data models for conversation service.

This module defines data structures used by the ChatOrchestrator
for managing conversation state and results.
"""
from dataclasses import dataclass, field
from typing import Optional, List, Any
from backend.domain.models.messages import BaseMessage
from backend.domain.models.streaming import StreamingChunk


@dataclass
class ConversationResult:
    """
    Result of executing a conversation turn.

    Attributes:
        final_message: The final message generated by the LLM
        streaming_message_id: Optional ID of the streaming message placeholder
        interrupted: Whether the conversation was interrupted by user
        iteration_count: Number of tool calling iterations performed
    """
    final_message: BaseMessage
    streaming_message_id: Optional[str] = None
    interrupted: bool = False
    iteration_count: int = 0


@dataclass
class StreamingState:
    """
    State maintained during streaming execution.

    This encapsulates all mutable state during a streaming conversation turn,
    making it easier to test and reason about the streaming logic.

    Attributes:
        message_id: Database ID of the streaming message placeholder
        collected_chunks: All streaming chunks received from LLM
        thinking_buffer: Accumulated thinking content
        text_buffer: Accumulated text content
        last_raw_response: Last raw response from LLM API (for usage metadata extraction)
    """
    message_id: str
    collected_chunks: List[StreamingChunk] = field(default_factory=list)
    thinking_buffer: str = ""
    text_buffer: str = ""
    last_raw_response: Optional[Any] = None  # Store last chunk for usage extraction

    def add_chunk(self, chunk: StreamingChunk) -> None:
        """
        Add a streaming chunk and update appropriate buffer.

        Args:
            chunk: The streaming chunk to add
        """
        self.collected_chunks.append(chunk)

        if chunk.chunk_type == "thinking":
            self.thinking_buffer += chunk.content
        elif chunk.chunk_type == "text":
            self.text_buffer += chunk.content

    def get_content_blocks(self) -> List[dict]:
        """
        Build content blocks for WebSocket transmission.

        Returns:
            List of content block dictionaries with type and content
        """
        content_blocks = []
        if self.thinking_buffer:
            content_blocks.append({"type": "thinking", "thinking": self.thinking_buffer})
        if self.text_buffer:
            content_blocks.append({"type": "text", "text": self.text_buffer})
        return content_blocks
