"""PFC Console Service for user Python command execution.

Application layer service for user PFC Python commands (CLI `>` prefix).
Provides foreground execution with Ctrl+B support.

Flow (aligned with user bash):
1. Save code as workspace/.user_console script
2. Submit via MCP pfc_execute_task
3. Create local task with returned task_id
4. Register with ForegroundRegistry for Ctrl+B signal
5. Poll for completion via MCP OR Ctrl+B signal
6. Return result or MoveToBackgroundRequest
"""

import asyncio
import logging
from typing import Any, Optional, Union, cast
from pathlib import Path
from dataclasses import dataclass
from datetime import datetime
from uuid import uuid4

logger = logging.getLogger(__name__)

from backend.infrastructure.pfc.task_manager import get_pfc_task_manager
from backend.infrastructure.pfc.foreground_registry import get_pfc_foreground_registry
from backend.shared.utils.mcp_utils import extract_mcp_text


# Caveat message for user PFC Python commands
PFC_CONSOLE_CAVEAT_MESSAGE = (
    "Caveat: The messages below were generated by the user while running local commands. "
    "DO NOT respond to these messages or otherwise consider them in your response "
    "unless the user explicitly asks you to."
)

USER_CONSOLE_DIR = ".user_console"


def build_console_description(code: str, max_length: int = 50) -> str:
    """Build a one-line preview for task descriptions."""
    first_line = code.splitlines()[0].strip() if code.splitlines() else ""
    if len(first_line) <= max_length:
        return first_line
    return first_line[: max_length - 3] + "..."


def create_console_script(workspace_path: Path, code: str, description: str) -> Path:
    """Create a user console script file in workspace/.user_console."""
    console_dir = workspace_path / USER_CONSOLE_DIR
    console_dir.mkdir(parents=True, exist_ok=True)

    stamp = datetime.now().strftime("%Y%m%d_%H%M%S_%f")
    script_name = f"console_{stamp}_{uuid4().hex[:6]}.py"
    script_path = console_dir / script_name

    content = (
        "# User Console Command\n"
        "# Auto-generated script for user console execution\n"
        f"# Description: {description}\n\n"
        f"{code}\n"
    )
    script_path.write_text(content, encoding="utf-8")
    return script_path


def format_pfc_console_context(
    code: str,
    task_id: str,
    output: str,
    error: Optional[str] = None,
) -> str:
    """Format PFC console result for LLM context injection."""
    return (
        f"<pfc-python>\n"
        f"<input>{code}</input>\n"
        f"<task_id>{task_id}</task_id>\n"
        f"<output>{output if output else ''}</output>\n"
        f"<error>{error if error else ''}</error>\n"
        f"</pfc-python>"
    )


def format_pfc_console_with_caveat(
    code: str,
    task_id: str,
    output: str,
    error: Optional[str] = None,
) -> str:
    """Format PFC console result with caveat prefix."""
    context = format_pfc_console_context(code, task_id, output, error)
    return f"{PFC_CONSOLE_CAVEAT_MESSAGE}\n{context}"


@dataclass
class PfcConsoleMoveToBackgroundRequest:
    """Request to move PFC console task to background.

    Returned when user presses Ctrl+B during foreground execution.
    """

    task_id: str
    reason: str = "user_request"


@dataclass
class PfcConsoleExecutionResult:
    """Result of PFC console execution."""

    task_id: str
    status: str  # "completed" or "failed"
    output: str
    error: Optional[str] = None
    result: Optional[object] = None
    elapsed_time: float = 0.0


@dataclass
class PfcConsoleForegroundHandle:
    """Handle for foreground PFC console execution with Ctrl+B support.

    Similar to bash's ForegroundExecutionHandle, but for WebSocket-based execution.
    Waits for either:
    - WebSocket response (script completed)
    - Move-to-background signal (Ctrl+B pressed)
    """

    task_id: str
    timeout_seconds: Optional[float] = None
    _move_to_bg_event: Optional[asyncio.Event] = None

    def __post_init__(self):
        if self._move_to_bg_event is None:
            self._move_to_bg_event = asyncio.Event()

    def request_move_to_background(self) -> None:
        """Signal to move task to background (called by registry on Ctrl+B)."""
        if self._move_to_bg_event is not None:
            self._move_to_bg_event.set()


class PfcConsoleService:
    """Service for user PFC console command execution with Ctrl+B support.

    Aligned with user bash pattern:
    - Saves code to workspace/.user_console script
    - Submits via pfc_execute_task (always background)
    - Polls pfc_check_task_status while listening for Ctrl+B
    """

    def __init__(self, workspace_path: Path, session_id: str):
        self.workspace_path = workspace_path
        self.session_id = session_id
        self._task_manager = get_pfc_task_manager()

    async def execute_foreground(
        self,
        code: str,
        timeout_ms: Optional[int] = None,
    ) -> tuple[
        Union[PfcConsoleExecutionResult, PfcConsoleMoveToBackgroundRequest, None],
        str,  # task_id
        Optional[str],  # error_message if failed early
    ]:
        """Execute code in foreground with Ctrl+B support.

        Aligned with user bash pattern:
        1. Save code as script and submit to pfc_execute_task
        2. Create local task and register Ctrl+B handle
        3. Poll pfc_check_task_status OR handle Ctrl+B signal
        4. Return completion result or MoveToBackgroundRequest

        Args:
            code: Python code to execute
            timeout_ms: Optional timeout in milliseconds

        Returns:
            Tuple of (wait_result, task_id, error_message)
        """
        code = code.strip()
        if not code:
            return None, "", None

        description = build_console_description(code)

        try:
            script_path = create_console_script(self.workspace_path, code, description)
        except Exception as e:
            return None, "", f"Failed to create console script: {e}"

        # 1. Submit via MCP — get task_id
        from backend.infrastructure.mcp.config import get_mcp_client_manager

        mcp_manager = get_mcp_client_manager()

        try:
            result = await mcp_manager.call_tool(
                "pfc_execute_task",
                {
                    "entry_script": str(script_path),
                    "description": description,
                    "timeout": timeout_ms // 1000 if timeout_ms else 30,
                },
            )
            if result.get("status") == "error":
                raise ConnectionError(result.get("message", "MCP tool call failed"))
        except ConnectionError as e:
            return None, "", f"PFC server not available: {e}"

        # 2. Extract task_id from response
        task_id = None
        structured = result.get("structuredContent")
        if isinstance(structured, dict):
            task_id = structured.get("task_id")
        if not task_id:
            text = extract_mcp_text(result)
            for line in text.splitlines():
                if line.strip().startswith("- task_id:"):
                    task_id = line.split(":", 1)[1].strip()
                    break
        if not task_id:
            return None, "", "Failed to extract task_id from MCP response"

        # 3. Create local task
        self._task_manager.create_task(
            task_id=task_id,
            session_id=self.session_id,
            script_path=str(script_path),
            description=description,
            source="user_console",
        )
        self._task_manager.update_status(task_id, "running")

        # 4. Create handle and register for Ctrl+B
        handle = PfcConsoleForegroundHandle(
            task_id=task_id,
            timeout_seconds=timeout_ms / 1000.0 if timeout_ms else None,
        )

        registry = get_pfc_foreground_registry()
        registry.register(self.session_id, cast(Any, handle))

        try:
            # 5. Poll for completion with Ctrl+B signal
            move_event = handle._move_to_bg_event
            if move_event is None:
                return None, task_id, "Foreground event not initialized"
            signal_task = asyncio.create_task(move_event.wait())
            timeout_seconds = timeout_ms / 1000.0 if timeout_ms else 60.0
            poll_start = asyncio.get_event_loop().time()

            while True:
                # Check Ctrl+B signal
                if signal_task.done():
                    return PfcConsoleMoveToBackgroundRequest(task_id=task_id, reason="user_request"), task_id, None

                # Check timeout
                elapsed = asyncio.get_event_loop().time() - poll_start
                if elapsed >= timeout_seconds:
                    signal_task.cancel()
                    return PfcConsoleMoveToBackgroundRequest(task_id=task_id, reason="timeout"), task_id, None

                # Poll task status via MCP
                try:
                    status_result = await mcp_manager.call_tool(
                        "pfc_check_task_status",
                        {
                            "task_id": task_id,
                            "wait_seconds": 1,
                        },
                    )
                    structured_status = status_result.get("structuredContent")
                    status_text = extract_mcp_text(status_result)

                    parsed_status = "running"
                    output = ""
                    error = None

                    if isinstance(structured_status, dict):
                        parsed_status = (structured_status.get("status") or "running").lower()
                        output = structured_status.get("output") or ""
                        error = structured_status.get("error")

                    is_terminal = parsed_status in {"completed", "failed", "interrupted"}

                    if not isinstance(structured_status, dict):
                        # Parse status from text fallback
                        for line in status_text.splitlines():
                            stripped = line.strip().lower()
                            if "status:" in stripped:
                                if "completed" in stripped or "success" in stripped:
                                    parsed_status = "completed"
                                    is_terminal = True
                                elif "failed" in stripped or "error" in stripped:
                                    parsed_status = "failed"
                                    is_terminal = True
                                elif "interrupted" in stripped:
                                    parsed_status = "interrupted"
                                    is_terminal = True

                    if is_terminal:
                        signal_task.cancel()
                        if not output:
                            output_section = False
                            output_lines = []
                            for line in status_text.splitlines():
                                if "Output" in line or "=== Script Output" in line:
                                    output_section = True
                                    continue
                                if output_section:
                                    output_lines.append(line)
                                elif line.strip().startswith("- error:") and not error:
                                    error = line.split(":", 1)[1].strip()

                            output = "\n".join(output_lines).strip()

                        self._task_manager.update_status(task_id, parsed_status, error=error)
                        if output:
                            self._task_manager.set_output(task_id, output)

                        return (
                            PfcConsoleExecutionResult(
                                task_id=task_id,
                                status=parsed_status,
                                output=output,
                                error=error,
                                elapsed_time=elapsed,
                            ),
                            task_id,
                            None,
                        )

                except Exception as e:
                    logger.warning(f"Poll error for console task {task_id}: {e}")

                await asyncio.sleep(1.0)

        except Exception as e:
            self._task_manager.update_status(task_id, "failed", error=str(e))
            return None, task_id, str(e)

        finally:
            registry.unregister(self.session_id)

    def process_completion(
        self,
        code: str,
        exec_result: PfcConsoleExecutionResult,
    ) -> str:
        """Process normal completion, return LLM context."""
        return format_pfc_console_with_caveat(
            code=code,
            task_id=exec_result.task_id,
            output=exec_result.output,
            error=exec_result.error,
        )

    async def process_backgrounded(
        self,
        code: str,
        task_id: str,
        bg_request: PfcConsoleMoveToBackgroundRequest,
    ) -> str:
        """Process Ctrl+B backgrounding, send notification, return LLM context."""
        if bg_request.reason == "user_request":
            output = f"Code execution backgrounded by user. Task ID: {task_id}"
        else:
            output = f"Code execution timed out, continuing in background. Task ID: {task_id}"

        # Send PFC task notification to frontend for monitoring
        # User console tasks are just PFC tasks with source="user_console"
        from backend.application.notifications.pfc_task_notification_service import (
            get_pfc_task_notification_service,
        )

        notification_service = get_pfc_task_notification_service()
        if notification_service is None:
            logger.warning("PFC task notification service unavailable while backgrounding %s", task_id)
            return format_pfc_console_with_caveat(
                code=code,
                task_id=task_id,
                output=output,
                error=None,
            )
        notification_service = cast(Any, notification_service)

        # Get script path from task manager
        task_info = self._task_manager.get_task(task_id)
        script_path = task_info.script_path if task_info else "user_console"
        description = build_console_description(code)

        # Send backgrounded notification and start polling
        await notification_service.notify_foreground_backgrounded(
            session_id=self.session_id,
            task_id=task_id,
            script_path=script_path,
            reason=bg_request.reason,
            elapsed_seconds=0.0,
            description=description,
            source="user_console",
        )
        await notification_service.start_polling(self.session_id)

        return format_pfc_console_with_caveat(
            code=code,
            task_id=task_id,
            output=output,
            error=None,
        )


def get_pfc_console_service(workspace_path: Path, session_id: str) -> PfcConsoleService:
    """Get PfcConsoleService instance."""
    return PfcConsoleService(workspace_path, session_id)
