"""PFC Console Service for user Python command execution.

Application layer service for user PFC Python commands (CLI `>` prefix).
Provides foreground execution with Ctrl+B support.

Flow (aligned with user bash):
1. Create task via TaskManager
2. Submit to pfc-bridge via MCP (run_in_background=True)
3. Register with ForegroundRegistry for Ctrl+B signal
4. Poll for completion via MCP OR Ctrl+B signal
5. Return result or MoveToBackgroundRequest
"""

import asyncio
import logging
from typing import Optional, Union
from pathlib import Path
from dataclasses import dataclass

logger = logging.getLogger(__name__)

from backend.infrastructure.pfc.task_manager import get_pfc_task_manager
from backend.infrastructure.pfc.foreground_registry import get_pfc_foreground_registry
from backend.shared.utils.mcp_utils import extract_mcp_text


# Caveat message for user PFC Python commands
PFC_CONSOLE_CAVEAT_MESSAGE = (
    "Caveat: The messages below were generated by the user while running local commands. "
    "DO NOT respond to these messages or otherwise consider them in your response "
    "unless the user explicitly asks you to."
)


def format_pfc_console_context(
    code: str,
    task_id: str,
    output: str,
    error: Optional[str] = None,
) -> str:
    """Format PFC console result for LLM context injection."""
    return (
        f"<pfc-python>\n"
        f"<input>{code}</input>\n"
        f"<task_id>{task_id}</task_id>\n"
        f"<output>{output if output else ''}</output>\n"
        f"<error>{error if error else ''}</error>\n"
        f"</pfc-python>"
    )


def format_pfc_console_with_caveat(
    code: str,
    task_id: str,
    output: str,
    error: Optional[str] = None,
) -> str:
    """Format PFC console result with caveat prefix."""
    context = format_pfc_console_context(code, task_id, output, error)
    return f"{PFC_CONSOLE_CAVEAT_MESSAGE}\n{context}"


@dataclass
class PfcConsoleMoveToBackgroundRequest:
    """Request to move PFC console task to background.

    Returned when user presses Ctrl+B during foreground execution.
    """
    task_id: str
    reason: str = "user_request"


@dataclass
class PfcConsoleExecutionResult:
    """Result of PFC console execution."""
    task_id: str
    status: str  # "completed" or "failed"
    output: str
    error: Optional[str] = None
    result: Optional[any] = None
    elapsed_time: float = 0.0


@dataclass
class PfcConsoleForegroundHandle:
    """Handle for foreground PFC console execution with Ctrl+B support.

    Similar to bash's ForegroundExecutionHandle, but for WebSocket-based execution.
    Waits for either:
    - WebSocket response (script completed)
    - Move-to-background signal (Ctrl+B pressed)
    """
    task_id: str
    timeout_seconds: Optional[float] = None
    _move_to_bg_event: asyncio.Event = None

    def __post_init__(self):
        if self._move_to_bg_event is None:
            self._move_to_bg_event = asyncio.Event()

    def request_move_to_background(self) -> None:
        """Signal to move task to background (called by registry on Ctrl+B)."""
        self._move_to_bg_event.set()


class PfcConsoleService:
    """Service for user PFC console command execution with Ctrl+B support.

    Aligned with user bash pattern:
    - Uses synchronous WebSocket call (run_in_background=False)
    - Wraps in asyncio.wait() with Ctrl+B signal
    - No polling needed
    """

    def __init__(self, workspace_path: Path, session_id: str):
        self.workspace_path = workspace_path
        self.session_id = session_id
        self._task_manager = get_pfc_task_manager()

    async def execute_foreground(
        self,
        code: str,
        timeout_ms: Optional[int] = None,
    ) -> tuple[
        Union[PfcConsoleExecutionResult, PfcConsoleMoveToBackgroundRequest, None],
        str,  # task_id
        Optional[str],  # error_message if failed early
    ]:
        """Execute code in foreground with Ctrl+B support.

        Aligned with user bash pattern:
        1. Create task
        2. Register handle for Ctrl+B
        3. Send synchronous WebSocket request (run_in_background=False)
        4. asyncio.wait() on response OR Ctrl+B signal
        5. Return result or MoveToBackgroundRequest

        Args:
            code: Python code to execute
            timeout_ms: Optional timeout in milliseconds

        Returns:
            Tuple of (wait_result, task_id, error_message)
        """
        code = code.strip()
        if not code:
            return None, "", None

        # 1. Create task
        task_id = self._task_manager.create_task(
            session_id=self.session_id,
            script_path="user_console",
            description=code[:50] + "..." if len(code) > 50 else code,
            source="user_console",
        )
        self._task_manager.update_status(task_id, "submitted")

        # 2. Get MCP client manager
        from backend.infrastructure.mcp.client import get_mcp_client_manager
        mcp_manager = get_mcp_client_manager()

        # 3. Create handle and register for Ctrl+B
        handle = PfcConsoleForegroundHandle(
            task_id=task_id,
            timeout_seconds=timeout_ms / 1000.0 if timeout_ms else None,
        )

        registry = get_pfc_foreground_registry()
        registry.register(self.session_id, handle)

        self._task_manager.update_status(task_id, "running")

        try:
            # 4. Submit via MCP with run_in_background=True, then poll locally
            try:
                result = await mcp_manager.call_tool("pfc_execute_code", {
                    "code": code,
                    "timeout": timeout_ms // 1000 if timeout_ms else 30,
                    "run_in_background": True,
                })
                if result.get("status") == "error":
                    raise ConnectionError(result.get("message", "MCP tool call failed"))
            except ConnectionError as e:
                self._task_manager.update_status(task_id, "failed", error=str(e))
                return None, task_id, f"PFC server not available: {e}"

            # Extract bridge task_id from response
            text = extract_mcp_text(result)
            bridge_task_id = None
            for line in text.splitlines():
                if line.strip().startswith("- task_id:"):
                    bridge_task_id = line.split(":", 1)[1].strip()
                    break

            self._task_manager.update_status(task_id, "running", bridge_task_id=bridge_task_id)

            # 5. Poll for completion with Ctrl+B signal
            poll_task_id = bridge_task_id or task_id
            signal_task = asyncio.create_task(handle._move_to_bg_event.wait())
            timeout_seconds = timeout_ms / 1000.0 if timeout_ms else 60.0
            poll_start = asyncio.get_event_loop().time()

            while True:
                # Check Ctrl+B signal
                if signal_task.done():
                    return PfcConsoleMoveToBackgroundRequest(
                        task_id=task_id, reason="user_request"
                    ), task_id, None

                # Check timeout
                elapsed = asyncio.get_event_loop().time() - poll_start
                if elapsed >= timeout_seconds:
                    signal_task.cancel()
                    return PfcConsoleMoveToBackgroundRequest(
                        task_id=task_id, reason="timeout"
                    ), task_id, None

                # Poll task status via MCP
                try:
                    status_result = await mcp_manager.call_tool("pfc_check_task_status", {
                        "task_id": poll_task_id,
                        "wait_seconds": 1,
                    })
                    status_text = extract_mcp_text(status_result)

                    # Parse status from text response
                    is_terminal = False
                    parsed_status = "running"
                    for line in status_text.splitlines():
                        stripped = line.strip().lower()
                        if "status:" in stripped:
                            if "completed" in stripped or "success" in stripped:
                                parsed_status = "completed"
                                is_terminal = True
                            elif "failed" in stripped or "error" in stripped:
                                parsed_status = "failed"
                                is_terminal = True
                            elif "interrupted" in stripped:
                                parsed_status = "interrupted"
                                is_terminal = True

                    if is_terminal:
                        signal_task.cancel()
                        # Extract output from status text
                        output = ""
                        error = None
                        output_section = False
                        output_lines = []
                        for line in status_text.splitlines():
                            if "Output:" in line or "=== Script Output" in line:
                                output_section = True
                                continue
                            if output_section:
                                output_lines.append(line)
                            elif line.strip().startswith("- error:"):
                                error = line.split(":", 1)[1].strip()

                        output = "\n".join(output_lines).strip()

                        self._task_manager.update_status(task_id, parsed_status, error=error)
                        if output:
                            self._task_manager.set_output(task_id, output)

                        return PfcConsoleExecutionResult(
                            task_id=task_id,
                            status=parsed_status,
                            output=output,
                            error=error,
                            elapsed_time=elapsed,
                        ), task_id, None

                except Exception as e:
                    logger.warning(f"Poll error for console task {task_id}: {e}")

                await asyncio.sleep(1.0)

        except Exception as e:
            self._task_manager.update_status(task_id, "failed", error=str(e))
            return None, task_id, str(e)

        finally:
            registry.unregister(self.session_id)

    def process_completion(
        self,
        code: str,
        exec_result: PfcConsoleExecutionResult,
    ) -> str:
        """Process normal completion, return LLM context."""
        return format_pfc_console_with_caveat(
            code=code,
            task_id=exec_result.task_id,
            output=exec_result.output,
            error=exec_result.error,
        )

    async def process_backgrounded(
        self,
        code: str,
        task_id: str,
        bg_request: PfcConsoleMoveToBackgroundRequest,
    ) -> str:
        """Process Ctrl+B backgrounding, send notification, return LLM context."""
        if bg_request.reason == "user_request":
            output = f"Code execution backgrounded by user. Task ID: {task_id}"
        else:
            output = f"Code execution timed out, continuing in background. Task ID: {task_id}"

        # Send PFC task notification to frontend for monitoring
        # User console tasks are just PFC tasks with source="user_console"
        from backend.application.notifications.pfc_task_notification_service import (
            get_pfc_task_notification_service,
        )
        notification_service = get_pfc_task_notification_service()

        # Get script path from task manager
        task_info = self._task_manager.get_task(task_id)
        script_path = task_info.script_path if task_info else "user_console"
        description = code[:50] + "..." if len(code) > 50 else code

        # Send backgrounded notification and start polling
        await notification_service.notify_foreground_backgrounded(
            session_id=self.session_id,
            task_id=task_id,
            script_path=script_path,
            reason=bg_request.reason,
            elapsed_seconds=0.0,
            description=description,
            source="user_console",
        )
        await notification_service.start_polling(self.session_id)

        return format_pfc_console_with_caveat(
            code=code,
            task_id=task_id,
            output=output,
            error=None,
        )


def get_pfc_console_service(workspace_path: Path, session_id: str) -> PfcConsoleService:
    """Get PfcConsoleService instance."""
    return PfcConsoleService(workspace_path, session_id)
